; LOUIS JENSEN       Sun Dec  8 23:54:42 2024
%INCLUDE "Along32.inc"
%INCLUDE "Macros_Along.inc"

SECTION .text                           
global  _start                          ; program dwwtest1

_start:                                 
        mov     eax, I33                
        add     eax, I33                
        mov     T0, eax                 
        mov     eax, I36                
        add     eax, I36                
        mov     T1, eax                 
        mov     eax, I39                
        add     eax, I39                
        mov     T2, eax                 
        mov     eax, I42                
        add     eax, I42                
        mov     T3, eax                 
        mov     eax, I45                
        add     eax, I45                
        mov     T4, eax                 
        mov     eax, I48                
        add     eax, I48                
        mov     T5, eax                 
        mov     eax, I51                
        add     eax, I51                
        mov     T6, eax                 
        mov     eax, I54                
        add     eax, I54                
        mov     T7, eax                 
        mov     eax, I57                
        add     eax, I57                
        mov     T8, eax                 
        mov     eax, I60                
        add     eax, I60                
        mov     T9, eax                 
        mov     eax, I63                
        add     eax, I63                
        mov     T10, eax                
        mov     eax, I65                
        add     eax, I65                
        mov     I62, eax                
        mov     eax, I69                
        imul    eax, I69                
        mov     eax, I72                
        imul    eax, I72                
        mov     T13, eax                
        mov     eax, I71                
        add     eax, I71                
        mov     eax, I76                
        imul    eax, I76                
        mov     T15, eax                
        mov     eax, I75                
        add     eax, I75                
        mov     eax, I80                
        imul    eax, I80                
        mov     T17, eax                
        mov     eax, I79                
        add     eax, I79                
        mov     eax, I84                
        imul    eax, I84                
        mov     T19, eax                
        mov     eax, I83                
        add     eax, I83                
        mov     eax, I88                
        imul    eax, I88                
        mov     T21, eax                
        mov     eax, I87                
        add     eax, I87                
        mov     eax, I92                
        imul    eax, I92                
        mov     T23, eax                
        mov     eax, I91                
        add     eax, I91                
        mov     eax, I96                
        imul    eax, I96                
        mov     T25, eax                
        mov     eax, I95                
        add     eax, I95                
        mov     eax, I100               
        imul    eax, I100               
        mov     T27, eax                
        mov     eax, I99                
        add     eax, I99                
        mov     eax, I104               
        imul    eax, I104               
        mov     T29, eax                
        mov     eax, I103               
        add     eax, I103               
        mov     eax, I108               
        imul    eax, I108               
        mov     T31, eax                
        mov     eax, I107               
        add     eax, I107               
        mov     eax, I112               
        imul    eax, I112               
        mov     T33, eax                
        mov     eax, I111               
        add     eax, I111               
        mov     T34, eax                
        mov     eax, I115               
        add     eax, I115               
        mov     I68, eax                
        mov     eax, I119               
        add     eax, I119               
        mov     T36, eax                
        mov     eax, I121               
        add     eax, I121               
        mov     T37, eax                
        mov     eax, I123               
        add     eax, I123               
        mov     T38, eax                
        mov     eax, I125               
        add     eax, I125               
        mov     T39, eax                
        mov     eax, I127               
        add     eax, I127               
        mov     T40, eax                
        mov     eax, I129               
        add     eax, I129               
        mov     T41, eax                
        mov     eax, I131               
        add     eax, I131               
        mov     T42, eax                
        mov     eax, I133               
        add     eax, I133               
        mov     T43, eax                
        mov     eax, I135               
        add     eax, I135               
        mov     T44, eax                
        mov     eax, I137               
        add     eax, I137               
        mov     T45, eax                
        mov     eax, I139               
        add     eax, I139               
        mov     T46, eax                
        mov     eax, I141               
        add     eax, I141               
        mov     T47, eax                
        mov     eax, I143               
        add     eax, I143               
        mov     T48, eax                
        mov     eax, I145               
        add     eax, I145               
        mov     T49, eax                
        mov     eax, I147               
        add     eax, I147               
        mov     T50, eax                
        mov     eax, I149               
        add     eax, I149               
        mov     T51, eax                
        mov     eax, I151               
        add     eax, I151               
        mov     T52, eax                
        mov     eax, I153               
        add     eax, I153               
        mov     T53, eax                
        mov     eax, I155               
        add     eax, I155               
        mov     T54, eax                
        mov     eax, I157               
        add     eax, I157               
        mov     T55, eax                
        mov     eax, I159               
        add     eax, I159               
        mov     T56, eax                
        mov     eax, I161               
        add     eax, I161               
        mov     T57, eax                
        mov     eax, I163               
        add     eax, I163               
        mov     T58, eax                
        mov     eax, I165               
        add     eax, I165               
        mov     I118, eax               
        mov     eax, I168               
        neg     eax                     
        mov     T60, eax                
        mov     eax, I169               
        add     eax, I169               
        mov     eax, I172               
        neg     eax                     
        mov     T62, eax                
        mov     eax, I171               
        add     eax, I171               
        mov     T63, eax                
        mov     eax, I175               
        sub     eax, I175               
        mov     eax, I178               
        neg     eax                     
        mov     T65, eax                
        mov     eax, I177               
        sub     eax, I177               
